general {
    lock_cmd = pidof hyprlock || hyprlock -c ~/.config/hypr/hyprlock/hyprlock.conf       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on && qs -p ~/.config/quickshell/bar ipc call clock refresh  # моніторм он + форс-оновлення годинника
}
# Screen dimming
listener {
    timeout = 150                               # 2.5 minutes
    on-timeout = brightnessctl -s set 10        # set monitor backlight to minimum
    on-resume = brightnessctl -r                # restore monitor backlight
}
# Screen locking
listener {
    timeout = 300                               # 5 minutes
    on-timeout = loginctl lock-session          # lock session
}
# Turn off monitors
listener {
    timeout = 600                               # 10 minutes
    on-timeout = hyprctl dispatch dpms off      # screen off when timeout passed
    on-resume = hyprctl dispatch dpms on        # screen on when activity is detected
}
# Suspend
listener {
    timeout = 1800                              # 30 minutes
    on-timeout = systemctl suspend              # suspend pc
}
