# modules/autostart.conf — mirrors hypr/modules/autostart.lua

exec-once=~/.config/quickshell/bar/reload.sh
exec-once=awww-daemon
exec-once=wl-paste --watch cliphist store
exec-once=hypridle
exec-once=swaync
exec-once=blueman-applet & nm-applet --indicator &
exec-once=~/edots-hypr/run.sh
exec-once=python3 ~/edots-hypr/tui-player/forks/player.py -d
